### ISSUE TITLE
RuntimeError while start training on Padova1 dataset

### ISSUE THREAD

**Issue by asifsetu** [leilamou/CSNet#1]
I have started first the visdom server on my Windows 10 PC then run the train.py to train Padova1 dataset. But I got the RuntimeError after running for a couple of epochs. Could you please suggest any solution to solve the issue. Thanks.

I am using windows 10 with python 3.6.6.

![image](https://user-images.githubusercontent.com/28484034/70808019-19fa1400-1dbf-11ea-96c9-deefb3f4da17.png)

**Comment by leilamou** [comment]
> I have started first the visdom server on my Windows 10 PC then run the train.py to train Padova1 dataset. But I got the RuntimeError after running for a couple of epochs. Could you please suggest any solution to solve the issue. Thanks.
> 
> I am using windows 10 with python 3.6.6.
> 
> ![image](https://user-images.githubusercontent.com/28484034/70808019-19fa1400-1dbf-11ea-96c9-deefb3f4da17.png)

You'd better change the `channels=3` into `channels=1` in `train.py`. The images in Padova1 are gray-scale images.
